language: erlang
script: "make && make test"
install:
  - sudo pip install numpy
  - sudo pip install pandas
  - sudo pip install matplotlib
  - sudo pip install sklearn
  - sudo pip install scipy
otp_release:
- 20.0
